name: Build Prod 

on:
  push:
    branches:
      - "prod"
    # hapus paths

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lks-voting-image # disesuaikan 
  ENV: "prod"
  ECS_SERVICE_WORKER: lks-worker-service # disesuaikan
  ECS_CLUSTER: lks-voting-cluster # disesuaikan
  WORKER_TASK_DEFINITION: worker/task-definition.json
  WORKER_CONTAINER_NAME: lks-worker-prod-container # disesuaikan

 # Vote
  ECS_SERVICE_VOTE: lks-vote-service
  VOTE_TASK_DEFINITION: vote/task-definition.json 
  VOTE_CONTAINER_NAME: lks-vote-prod-container   

  # Result
  ECS_SERVICE_RESULT: lks-result-service
  RESULT_TASK_DEFINITION: result/task-definition.json
  RESULT_CONTAINER_NAME: lks-result-prod-container


permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f worker/Dockerfile ./worker
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG
        echo "::set-output name=worker_image::$ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG"

    - name: End Build
      run: echo "Build Success"

  deploy:
    name: Deploy Application to Production
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set Variable
      id: set-vars
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # edit bagian ini
        ECR_REPOSITORY: lks-voting-image
        WORKER_IMAGE_TAG: worker-prod-latest
        VOTE_IMAGE_TAG: vote-prod-latest
        RESULT_IMAGE_TAG: result-prod-latest
      run: |
        echo "::set-output name=worker_image::$ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG"
        echo "::set-output name=vote_image::$ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG"
        echo "::set-output name=result_image::$ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG"

    # Worker
    - name: Fill in the new image ID in the Amazon ECS task definition (Worker)
      id: task-def-worker
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.WORKER_TASK_DEFINITION }}
        container-name: ${{ env.WORKER_CONTAINER_NAME }}
        image: ${{ steps.set-vars.outputs.worker_image }}

    - name: Deploy Amazon ECS task definition Worker
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-worker.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_WORKER }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    # Vote
    - name: Fill in the new image ID in the Amazon ECS task definition (Vote)
      id: task-def-vote
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.VOTE_TASK_DEFINITION }}
        container-name: ${{ env.VOTE_CONTAINER_NAME }}
        image: ${{ steps.set-vars.outputs.vote_image }}

    - name: Deploy Amazon ECS task definition Vote
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-vote.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_VOTE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    # Result
    - name: Fill in the new image ID in the Amazon ECS task definition (Result)
      id: task-def-result
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.RESULT_TASK_DEFINITION }}
        container-name: ${{ env.RESULT_CONTAINER_NAME }}
        image: ${{ steps.set-vars.outputs.result_image }}

    - name: Deploy Amazon ECS task definition Result
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-result.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_RESULT }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
  
  notif:
    name: Sent Notification
    needs: deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:    
    - name: Publish Message To SNS Subscribers
      env:
        TOPIC_ARN: ${{ secrets.AWS_SNS_ARN }}
        # tambah credential
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: us-east-1
      run: aws sns publish --topic-arn $TOPIC_ARN --subject "Hello, from Indonesia" --message "New Version Is Released"