  name: Build Dev

  on:
    push:
      branches:
        - "dev"

  env:
    AWS_REGION: us-east-1                 
    ECR_REPOSITORY: voting-app # nanti disesuaikan
    ENV: "dev"

  permissions:
    id-token: write
    contents: read

  jobs:
    build:
      name: Build Image Production
      runs-on: ubuntu-latest
      environment: Production
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f worker/Dockerfile ./worker
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG
          echo "::set-output name=worker_image::$ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG"

      - name: End Build
        run: echo "Build Success"

    node1:
      name: Example Pull Image on node1
      needs: build  
      # metrix 
      strategy:
        matrix:
          node: [node1, node2]
      runs-on: ${{ matrix.node }}
      steps:
        - name: Update runner's docker Version, as worker module requires it
          run: |
            docker --version

        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ env.AWS_REGION }}
            
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
    
        - name: Pull image
          id: pull-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: voting-app
            WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
          run: |
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG

    deploy:  
      name: Example Deploy Application into docker swarm
      needs: node1
      runs-on: master
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Deploy application images to Docker Swarm
          run: |
            docker node ls
            docker service ls
            docker stack ls
            docker stack rm stackdemo
            sleep 30
            docker stack deploy --compose-file docker-stack.yml stackdemo